-- Create table userinfos

CREATE TABLE IF NOT EXISTS userinfos
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(50),
    email        VARCHAR(100),
    passwordHash VARCHAR(30),
    role         INTEGER
);

-- Create table events

CREATE TABLE IF NOT EXISTS events
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(100),
    description VARCHAR(500),
    date        DATE,
    maxPlayers  INTEGER,
    price       NUMERIC(10,2),
    status      INTEGER,
    organizer   VARCHAR(100)
);

-- Create table registrations

CREATE TABLE IF NOT EXISTS registrations
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userId  BIGINT references userinfos (id),
    eventId BIGINT references events (id),
    status  INTEGER
);

CREATE INDEX idx_registrations_user
    ON registrations(userId);

CREATE INDEX idx_registrations_event
    ON registrations(eventId);